runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/packages.*
  script: api.packages_api.app

- url: /api/categories.*
  script: api.categories_api.app

libraries:
- name: webapp2
  version: "2.5.2"
